name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [truffleruby-head]
        appraisal: ["rails-6.0", "rails-6.1", "rails-7.0"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Set system gem command
        run: gem update --system

      - name: Install bundler
        run: gem install bundler

      - name: Bundle for Appraisal
        run: bundle

      - name: Install Appraisal dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle

      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec
